package holdemcalc.gui;

import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import holdemcalc.R;
import holdemcalc.activities.CalcActivity;

public class EventHandler {

    public static void initListeners(CalcActivity activity) {
        //diamonds
        View twodButton = activity.findViewById(R.id.twod);
        View threedButton = activity.findViewById(R.id.threed);
        View fourdButton = activity.findViewById(R.id.fourd);
        View fivedButton = activity.findViewById(R.id.fived);
        View sixdButton = activity.findViewById(R.id.sixd);
        View sevendButton = activity.findViewById(R.id.sevend);
        View eightdButton = activity.findViewById(R.id.eightd);
        View ninedButton = activity.findViewById(R.id.nined);
        View tendButton = activity.findViewById(R.id.tend);
        View jackdButton = activity.findViewById(R.id.jackd);
        View queendButton = activity.findViewById(R.id.queend);
        View kingdButton = activity.findViewById(R.id.kingd);
        View acedButton = activity.findViewById(R.id.aced);
        twodButton.setOnClickListener(activity);
        threedButton.setOnClickListener(activity);
        fourdButton.setOnClickListener(activity);
        fivedButton.setOnClickListener(activity);
        sixdButton.setOnClickListener(activity);
        sevendButton.setOnClickListener(activity);
        eightdButton.setOnClickListener(activity);
        ninedButton.setOnClickListener(activity);
        tendButton.setOnClickListener(activity);
        jackdButton.setOnClickListener(activity);
        queendButton.setOnClickListener(activity);
        kingdButton.setOnClickListener(activity);
        acedButton.setOnClickListener(activity);

        //hearts
        View twohButton = activity.findViewById(R.id.twoh);
        View threehButton = activity.findViewById(R.id.threeh);
        View fourhButton = activity.findViewById(R.id.fourh);
        View fivehButton = activity.findViewById(R.id.fiveh);
        View sixhButton = activity.findViewById(R.id.sixh);
        View sevenhButton = activity.findViewById(R.id.sevenh);
        View eighthButton = activity.findViewById(R.id.eighth);
        View ninehButton = activity.findViewById(R.id.nineh);
        View tenhButton = activity.findViewById(R.id.tenh);
        View jackhButton = activity.findViewById(R.id.jackh);
        View queenhButton = activity.findViewById(R.id.queenh);
        View kinghButton = activity.findViewById(R.id.kingh);
        View acehButton = activity.findViewById(R.id.aceh);
        twohButton.setOnClickListener(activity);
        threehButton.setOnClickListener(activity);
        fourhButton.setOnClickListener(activity);
        fivehButton.setOnClickListener(activity);
        sixhButton.setOnClickListener(activity);
        sevenhButton.setOnClickListener(activity);
        eighthButton.setOnClickListener(activity);
        ninehButton.setOnClickListener(activity);
        tenhButton.setOnClickListener(activity);
        jackhButton.setOnClickListener(activity);
        queenhButton.setOnClickListener(activity);
        kinghButton.setOnClickListener(activity);
        acehButton.setOnClickListener(activity);

        //clubs
        View twocButton = activity.findViewById(R.id.twoc);
        View threecButton = activity.findViewById(R.id.threec);
        View fourcButton = activity.findViewById(R.id.fourc);
        View fivecButton = activity.findViewById(R.id.fivec);
        View sixcButton = activity.findViewById(R.id.sixc);
        View sevencButton = activity.findViewById(R.id.sevenc);
        View eightcButton = activity.findViewById(R.id.eightc);
        View ninecButton = activity.findViewById(R.id.ninec);
        View tencButton = activity.findViewById(R.id.tenc);
        View jackcButton = activity.findViewById(R.id.jackc);
        View queencButton = activity.findViewById(R.id.queenc);
        View kingcButton = activity.findViewById(R.id.kingc);
        View acecButton = activity.findViewById(R.id.acec);
        twocButton.setOnClickListener(activity);
        threecButton.setOnClickListener(activity);
        fourcButton.setOnClickListener(activity);
        fivecButton.setOnClickListener(activity);
        sixcButton.setOnClickListener(activity);
        sevencButton.setOnClickListener(activity);
        eightcButton.setOnClickListener(activity);
        ninecButton.setOnClickListener(activity);
        tencButton.setOnClickListener(activity);
        jackcButton.setOnClickListener(activity);
        queencButton.setOnClickListener(activity);
        kingcButton.setOnClickListener(activity);
        acecButton.setOnClickListener(activity);

        //spades
        View twosButton = activity.findViewById(R.id.twos);
        View threesButton = activity.findViewById(R.id.threes);
        View foursButton = activity.findViewById(R.id.fours);
        View fivesButton = activity.findViewById(R.id.fives);
        View sixsButton = activity.findViewById(R.id.sixs);
        View sevensButton = activity.findViewById(R.id.sevens);
        View eightsButton = activity.findViewById(R.id.eights);
        View ninesButton = activity.findViewById(R.id.nines);
        View tensButton = activity.findViewById(R.id.tens);
        View jacksButton = activity.findViewById(R.id.jacks);
        View queensButton = activity.findViewById(R.id.queens);
        View kingsButton = activity.findViewById(R.id.kings);
        View acesButton = activity.findViewById(R.id.aces);
        twosButton.setOnClickListener(activity);
        threesButton.setOnClickListener(activity);
        foursButton.setOnClickListener(activity);
        fivesButton.setOnClickListener(activity);
        sixsButton.setOnClickListener(activity);
        sevensButton.setOnClickListener(activity);
        eightsButton.setOnClickListener(activity);
        ninesButton.setOnClickListener(activity);
        tensButton.setOnClickListener(activity);
        jacksButton.setOnClickListener(activity);
        queensButton.setOnClickListener(activity);
        kingsButton.setOnClickListener(activity);
        acesButton.setOnClickListener(activity);

        //resetCalculator
        View clr = activity.findViewById(R.id.clear);
        clr.setOnClickListener(activity);
    }

    public static void handleClick(CalcActivity calcActivity, View v) {
        switch (v.getId()) {
            //resetCalculator gui
            case R.id.clear:
                resetCalculator(calcActivity);
                break;
            //diamond case
            case R.id.twod:
                ImageView playerimage2 = calcActivity.getNextview();
                playerimage2.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.twod)));
                View twodButton = calcActivity.findViewById(R.id.twod);
                twodButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 2;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 2;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 2;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 2;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 2;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 2;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 2;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 2;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 2;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.threed:
                ImageView playerimage3 = calcActivity.getNextview();
                playerimage3.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.threed)));
                View threedButton = calcActivity.findViewById(R.id.threed);
                threedButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 6;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 6;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 6;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 6;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 6;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 6;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 6;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 6;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 6;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.fourd:
                ImageView playerimage4 = calcActivity.getNextview();
                playerimage4.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.fourd)));
                View fourdButton = calcActivity.findViewById(R.id.fourd);
                fourdButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 10;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 10;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 10;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 10;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 10;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 10;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 10;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 10;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 10;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.fived:
                ImageView playerimage5 = calcActivity.getNextview();
                playerimage5.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.fived)));
                View fivedButton = calcActivity.findViewById(R.id.fived);
                fivedButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 14;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 14;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 14;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 14;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 14;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 14;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 14;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 14;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 14;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.sixd:
                ImageView playerimage6 = calcActivity.getNextview();
                playerimage6.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.sixd)));
                View sixdButton = calcActivity.findViewById(R.id.sixd);
                sixdButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 18;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 18;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 18;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 18;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 18;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 18;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 18;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 18;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 18;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.sevend:
                ImageView playerimage7 = calcActivity.getNextview();
                playerimage7.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.sevend)));
                View sevendButton = calcActivity.findViewById(R.id.sevend);
                sevendButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 22;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 22;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 22;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 22;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 22;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 22;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 22;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 22;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 22;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.eightd:
                ImageView playerimage8 = calcActivity.getNextview();
                playerimage8.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.eightd)));
                View eightdButton = calcActivity.findViewById(R.id.eightd);
                eightdButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 26;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 26;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 26;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 26;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 26;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 26;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 26;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 26;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 26;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.nined:
                ImageView playerimage9 = calcActivity.getNextview();
                playerimage9.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.nined)));
                View ninedButton = calcActivity.findViewById(R.id.nined);
                ninedButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 30;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 30;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 30;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 30;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 30;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 30;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 30;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 30;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 30;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.tend:
                ImageView playerimage10 = calcActivity.getNextview();
                playerimage10.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.tend)));
                View tendButton = calcActivity.findViewById(R.id.tend);
                tendButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 34;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 34;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 34;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 34;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 34;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 34;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 34;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 34;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 34;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.jackd:
                ImageView playerimage11 = calcActivity.getNextview();
                playerimage11.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.jd)));
                View jackdButton = calcActivity.findViewById(R.id.jackd);
                jackdButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 38;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 38;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 38;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 38;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 38;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 38;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 38;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 38;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 38;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.queend:
                ImageView playerimage12 = calcActivity.getNextview();
                playerimage12.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.qd)));
                View queendButton = calcActivity.findViewById(R.id.queend);
                queendButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 42;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 42;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 42;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 42;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 42;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 42;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 42;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 42;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 42;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.kingd:
                ImageView playerimage13 = calcActivity.getNextview();
                playerimage13.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.kd)));
                View kingdButton = calcActivity.findViewById(R.id.kingd);
                kingdButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 46;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 46;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 46;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 46;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 46;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 46;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 46;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 46;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 46;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.aced:
                ImageView playerimage14 = calcActivity.getNextview();
                playerimage14.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.ad)));
                View acedButton = calcActivity.findViewById(R.id.aced);
                acedButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 50;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 50;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 50;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 50;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 50;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 50;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 50;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 50;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 50;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            //SRCA

            case R.id.twoh:
                ImageView playerimage15 = calcActivity.getNextview();
                playerimage15.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.twoh)));
                View twohButton = calcActivity.findViewById(R.id.twoh);
                twohButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 3;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 3;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 3;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 3;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 3;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 3;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 3;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 3;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 3;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.threeh:
                ImageView playerimage16 = calcActivity.getNextview();
                playerimage16.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.threeh)));
                View threehButton = calcActivity.findViewById(R.id.threeh);
                threehButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 7;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 7;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 7;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 7;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 7;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 7;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 7;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 7;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 7;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.fourh:
                ImageView playerimage17 = calcActivity.getNextview();
                playerimage17.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.fourh)));
                View fourhButton = calcActivity.findViewById(R.id.fourh);
                fourhButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 11;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 11;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 11;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 11;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 11;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 11;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 11;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 11;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 11;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.fiveh:
                ImageView playerimage18 = calcActivity.getNextview();
                playerimage18.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.fiveh)));
                View fivehButton = calcActivity.findViewById(R.id.fiveh);
                fivehButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 15;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 15;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 15;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 15;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 15;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 15;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 15;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 15;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 15;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.sixh:
                ImageView playerimage19 = calcActivity.getNextview();
                playerimage19.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.sixh)));
                View sixhButton = calcActivity.findViewById(R.id.sixh);
                sixhButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 19;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 19;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 19;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 19;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 19;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 19;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 19;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 19;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 19;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.sevenh:
                ImageView playerimage20 = calcActivity.getNextview();
                playerimage20.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.sevenh)));
                View sevenhButton = calcActivity.findViewById(R.id.sevenh);
                sevenhButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 23;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 23;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 23;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 23;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 23;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 23;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 23;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 23;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 23;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.eighth:
                ImageView playerimage21 = calcActivity.getNextview();
                playerimage21.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.eighth)));
                View eighthButton = calcActivity.findViewById(R.id.eighth);
                eighthButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 27;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 27;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 27;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 27;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 27;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 27;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 27;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 27;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 27;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.nineh:
                ImageView playerimage22 = calcActivity.getNextview();
                playerimage22.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.nineh)));
                View ninehButton = calcActivity.findViewById(R.id.nineh);
                ninehButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 31;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 31;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 31;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 31;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 31;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 31;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 31;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 31;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 31;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.tenh:
                ImageView playerimage23 = calcActivity.getNextview();
                playerimage23.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.tenh)));
                View tenhButton = calcActivity.findViewById(R.id.tenh);
                tenhButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 35;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 35;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 35;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 35;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 35;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 35;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 35;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 35;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 35;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.jackh:
                ImageView playerimage24 = calcActivity.getNextview();
                playerimage24.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.jh)));
                View jackhButton = calcActivity.findViewById(R.id.jackh);
                jackhButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 39;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 39;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 39;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 39;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 39;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 39;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 39;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 39;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 39;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.queenh:
                ImageView playerimage25 = calcActivity.getNextview();
                playerimage25.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.qh)));
                View queenhButton = calcActivity.findViewById(R.id.queenh);
                queenhButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 43;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 43;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 43;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 43;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 43;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 43;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 43;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 43;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 43;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.kingh:
                ImageView playerimage26 = calcActivity.getNextview();
                playerimage26.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.kh)));
                View kinghButton = calcActivity.findViewById(R.id.kingh);
                kinghButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 47;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 47;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 47;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 47;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 47;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 47;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 47;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 47;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 47;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.aceh:
                ImageView playerimage27 = calcActivity.getNextview();
                playerimage27.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.ah)));
                View acehButton = calcActivity.findViewById(R.id.aceh);
                acehButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 51;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 51;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 51;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 51;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 51;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 51;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 51;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 51;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 51;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            //TREF!!

            case R.id.twoc:
                ImageView playerimage28 = calcActivity.getNextview();
                playerimage28.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.twoc)));
                View twocButton = calcActivity.findViewById(R.id.twoc);
                twocButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 1;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 1;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 1;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 1;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 1;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 1;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 1;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 1;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 1;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.threec:
                ImageView playerimage29 = calcActivity.getNextview();
                playerimage29.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.threec)));
                View threecButton = calcActivity.findViewById(R.id.threec);
                threecButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 5;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 5;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 5;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 5;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 5;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 5;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 5;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 5;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 5;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.fourc:
                ImageView playerimage30 = calcActivity.getNextview();
                playerimage30.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.fourc)));
                View fourcButton = calcActivity.findViewById(R.id.fourc);
                fourcButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 9;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 9;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 9;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 9;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 9;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 9;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 9;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 9;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 9;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.fivec:
                ImageView playerimage31 = calcActivity.getNextview();
                playerimage31.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.fivec)));
                View fivecButton = calcActivity.findViewById(R.id.fivec);
                fivecButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 13;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 13;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 13;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 13;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 13;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 13;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 13;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 13;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 13;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.sixc:
                ImageView playerimage32 = calcActivity.getNextview();
                playerimage32.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.sixc)));
                View sixcButton = calcActivity.findViewById(R.id.sixc);
                sixcButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 17;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 17;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 17;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 17;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 17;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 17;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 17;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 17;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 17;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.sevenc:
                ImageView playerimage33 = calcActivity.getNextview();
                playerimage33.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.sevenc)));
                View sevencButton = calcActivity.findViewById(R.id.sevenc);
                sevencButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 21;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 21;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 21;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 21;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 21;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 21;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 21;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 21;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 21;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.eightc:
                ImageView playerimage34 = calcActivity.getNextview();
                playerimage34.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.eightc)));
                View eightcButton = calcActivity.findViewById(R.id.eightc);
                eightcButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 25;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 25;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 25;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 25;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 25;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 25;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 25;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 25;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 25;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.ninec:
                ImageView playerimage35 = calcActivity.getNextview();
                playerimage35.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.ninec)));
                View ninecButton = calcActivity.findViewById(R.id.ninec);
                ninecButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 29;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 29;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 29;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 29;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 29;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 29;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 29;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 29;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 29;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.tenc:
                ImageView playerimage36 = calcActivity.getNextview();
                playerimage36.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.tenc)));
                View tencButton = calcActivity.findViewById(R.id.tenc);
                tencButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 33;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 33;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 33;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 33;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 33;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 33;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 33;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 33;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 33;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.jackc:
                ImageView playerimage37 = calcActivity.getNextview();
                playerimage37.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.jc)));
                View jackcButton = calcActivity.findViewById(R.id.jackc);
                jackcButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 37;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 37;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 37;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 37;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 37;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 37;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 37;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 37;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 37;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.queenc:
                ImageView playerimage38 = calcActivity.getNextview();
                playerimage38.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.qc)));
                View queencButton = calcActivity.findViewById(R.id.queenc);
                queencButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 41;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 41;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 41;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 41;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 41;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 41;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 41;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 41;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 41;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.kingc:
                ImageView playerimage39 = calcActivity.getNextview();
                playerimage39.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.kc)));
                View kingcButton = calcActivity.findViewById(R.id.kingc);
                kingcButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 45;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 45;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 45;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 45;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 45;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 45;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 45;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 45;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 45;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.acec:
                ImageView playerimage40 = calcActivity.getNextview();
                playerimage40.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.ac)));
                View acecButton = calcActivity.findViewById(R.id.acec);
                acecButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 49;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 49;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 49;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 49;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 49;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 49;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 49;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 49;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 49;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            //PIKOVI


            case R.id.twos:
                ImageView playerimage41 = calcActivity.getNextview();
                playerimage41.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.twos)));
                View twosButton = calcActivity.findViewById(R.id.twos);
                twosButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 4;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 4;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 4;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 4;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 4;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 4;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 4;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 4;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 4;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.threes:
                ImageView playerimage42 = calcActivity.getNextview();
                playerimage42.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.threes)));
                View threesButton = calcActivity.findViewById(R.id.threes);
                threesButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 8;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 8;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 8;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 8;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 8;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 8;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 8;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 8;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 8;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.fours:
                ImageView playerimage43 = calcActivity.getNextview();
                playerimage43.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.fours)));
                View foursButton = calcActivity.findViewById(R.id.fours);
                foursButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 12;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 12;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 12;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 12;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 12;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 12;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 12;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 12;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 12;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.fives:
                ImageView playerimage44 = calcActivity.getNextview();
                playerimage44.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.fives)));
                View fivesButton = calcActivity.findViewById(R.id.fives);
                fivesButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 16;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 16;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 16;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 16;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 16;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 16;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 16;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 16;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 16;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;

            case R.id.sixs:
                ImageView playerimage45 = calcActivity.getNextview();
                playerimage45.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.sixs)));
                View sixsButton = calcActivity.findViewById(R.id.sixs);
                sixsButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 20;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 20;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 20;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 20;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 20;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 20;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 20;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 20;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 20;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.sevens:
                ImageView playerimage46 = calcActivity.getNextview();
                playerimage46.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.sevens)));
                View sevensButton = calcActivity.findViewById(R.id.sevens);
                sevensButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 24;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 24;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 24;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 24;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 24;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 24;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 24;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 24;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 24;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.eights:
                ImageView playerimage47 = calcActivity.getNextview();
                playerimage47.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.eights)));
                View eightsButton = calcActivity.findViewById(R.id.eights);
                eightsButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 28;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 28;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 28;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 28;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 28;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 28;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 28;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 28;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 28;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.nines:
                ImageView playerimage48 = calcActivity.getNextview();
                playerimage48.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.nines)));
                View ninesButton = calcActivity.findViewById(R.id.nines);
                ninesButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 32;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 32;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 32;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 32;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 32;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 32;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 32;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 32;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 32;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.tens:
                ImageView playerimage49 = calcActivity.getNextview();
                playerimage49.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.tens)));
                View tensButton = calcActivity.findViewById(R.id.tens);
                tensButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 36;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 36;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 36;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 36;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 36;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 36;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 36;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 36;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 36;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.jacks:
                ImageView playerimage50 = calcActivity.getNextview();
                playerimage50.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.js)));
                View jacksButton = calcActivity.findViewById(R.id.jacks);
                jacksButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 40;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 40;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 40;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 40;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 40;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 40;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 40;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 40;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 40;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.queens:
                ImageView playerimage51 = calcActivity.getNextview();
                playerimage51.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.qs)));
                View queensButton = calcActivity.findViewById(R.id.queens);
                queensButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 44;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 44;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 44;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 44;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 44;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 44;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 44;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 44;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 44;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.kings:
                ImageView playerimage52 = calcActivity.getNextview();
                playerimage52.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.ks)));
                View kingsButton = calcActivity.findViewById(R.id.kings);
                kingsButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 48;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 48;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 48;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 48;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 48;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 48;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 48;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 48;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 48;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
            case R.id.aces:
                ImageView playerimage53 = calcActivity.getNextview();
                playerimage53.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.as)));
                View acesButton = calcActivity.findViewById(R.id.aces);
                acesButton.setEnabled(false);
                if (calcActivity.cardPointer == 1) calcActivity.playerOneCardOne = 52;
                if (calcActivity.cardPointer == 2) calcActivity.playerOneCardTwo = 52;
                if (calcActivity.cardPointer == 3) calcActivity.playerTwoCardOne = 52;
                if (calcActivity.cardPointer == 4) calcActivity.playerTwoCardTwo = 52;
                if (calcActivity.cardPointer == 5) calcActivity.flopCard1 = 52;
                if (calcActivity.cardPointer == 6) calcActivity.flopCard2 = 52;
                if (calcActivity.cardPointer == 7) calcActivity.flopCard3 = 52;
                if (calcActivity.cardPointer == 8) calcActivity.turnCard = 52;
                if (calcActivity.cardPointer == 9) calcActivity.riverCard = 52;
                calcActivity.cardPointer++;
                calcActivity.setNextview(calcActivity.cardPointer);
                break;
        }
    }

    public static void resetCalculator(CalcActivity calcActivity){
    	//turn card face down
    	ImageView a = (ImageView) calcActivity.findViewById(R.id.player1card1);
    	a.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.backcard)));
    	ImageView b = (ImageView) calcActivity.findViewById(R.id.player1card2);
    	b.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.backcard)));
    	ImageView c = (ImageView) calcActivity.findViewById(R.id.player2card1);
    	c.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.backcard)));
    	ImageView d = (ImageView) calcActivity.findViewById(R.id.player2card2);
    	d.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.backcard)));
    	ImageView e = (ImageView) calcActivity.findViewById(R.id.flop1);
    	e.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.backcard)));
    	ImageView f = (ImageView) calcActivity.findViewById(R.id.flop2);
    	f.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.backcard)));
    	ImageView g = (ImageView) calcActivity.findViewById(R.id.flop3);
    	g.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.backcard)));
    	ImageView h = (ImageView) calcActivity.findViewById(R.id.turn);
    	h.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.backcard)));
    	ImageView i = (ImageView) calcActivity.findViewById(R.id.river);
    	i.setImageDrawable((calcActivity.getResources().getDrawable(R.drawable.backcard)));
    	//enable all cards
    	//diamonds
    	View twodButton = calcActivity.findViewById(R.id.twod);
		twodButton.setEnabled(true);
		View threedButton = calcActivity.findViewById(R.id.threed);
		threedButton.setEnabled(true);
		View fourdButton = calcActivity.findViewById(R.id.fourd);
		fourdButton.setEnabled(true);
		View fivedButton = calcActivity.findViewById(R.id.fived);
		fivedButton.setEnabled(true);
		View sixdButton = calcActivity.findViewById(R.id.sixd);
		sixdButton.setEnabled(true);
		View sevendButton = calcActivity.findViewById(R.id.sevend);
		sevendButton.setEnabled(true);
		View eightdButton = calcActivity.findViewById(R.id.eightd);
		eightdButton.setEnabled(true);
		View ninedButton = calcActivity.findViewById(R.id.nined);
		ninedButton.setEnabled(true);
		View tendButton = calcActivity.findViewById(R.id.tend);
		tendButton.setEnabled(true);
		View jackdButton = calcActivity.findViewById(R.id.jackd);
		jackdButton.setEnabled(true);
		View queendButton = calcActivity.findViewById(R.id.queend);
		queendButton.setEnabled(true);
		View kingdButton = calcActivity.findViewById(R.id.kingd);
		kingdButton.setEnabled(true);
		View acedButton = calcActivity.findViewById(R.id.aced);
		acedButton.setEnabled(true);
		//hearts
		View twohButton = calcActivity.findViewById(R.id.twoh);
		twohButton.setEnabled(true);
		View threehButton = calcActivity.findViewById(R.id.threeh);
		threehButton.setEnabled(true);
		View fourhButton = calcActivity.findViewById(R.id.fourh);
		fourhButton.setEnabled(true);
		View fivehButton = calcActivity.findViewById(R.id.fiveh);
		fivehButton.setEnabled(true);
		View sixhButton = calcActivity.findViewById(R.id.sixh);
		sixhButton.setEnabled(true);
		View sevenhButton = calcActivity.findViewById(R.id.sevenh);
		sevenhButton.setEnabled(true);
		View eighthButton = calcActivity.findViewById(R.id.eighth);
		eighthButton.setEnabled(true);
		View ninehButton = calcActivity.findViewById(R.id.nineh);
		ninehButton.setEnabled(true);
		View tenhButton = calcActivity.findViewById(R.id.tenh);
		tenhButton.setEnabled(true);
		View jackhButton = calcActivity.findViewById(R.id.jackh);
		jackhButton.setEnabled(true);
		View queenhButton = calcActivity.findViewById(R.id.queenh);
		queenhButton.setEnabled(true);
		View kinghButton = calcActivity.findViewById(R.id.kingh);
		kinghButton.setEnabled(true);
		View acehButton = calcActivity.findViewById(R.id.aceh);
		acehButton.setEnabled(true);
		//clubs
		View twocButton = calcActivity.findViewById(R.id.twoc);
		twocButton.setEnabled(true);
		View threecButton = calcActivity.findViewById(R.id.threec);
		threecButton.setEnabled(true);
		View fourcButton = calcActivity.findViewById(R.id.fourc);
		fourcButton.setEnabled(true);
		View fivecButton = calcActivity.findViewById(R.id.fivec);
		fivecButton.setEnabled(true);
		View sixcButton = calcActivity.findViewById(R.id.sixc);
		sixcButton.setEnabled(true);
		View sevencButton = calcActivity.findViewById(R.id.sevenc);
		sevencButton.setEnabled(true);
		View eightcButton = calcActivity.findViewById(R.id.eightc);
		eightcButton.setEnabled(true);
		View ninecButton = calcActivity.findViewById(R.id.ninec);
		ninecButton.setEnabled(true);
		View tencButton = calcActivity.findViewById(R.id.tenc);
		tencButton.setEnabled(true);
		View jackcButton = calcActivity.findViewById(R.id.jackc);
		jackcButton.setEnabled(true);
		View queencButton = calcActivity.findViewById(R.id.queenc);
		queencButton.setEnabled(true);
		View kingcButton = calcActivity.findViewById(R.id.kingc);
		kingcButton.setEnabled(true);
		View acecButton = calcActivity.findViewById(R.id.acec);
		acecButton.setEnabled(true);
		//spades
		View twosButton = calcActivity.findViewById(R.id.twos);
		twosButton.setEnabled(true);
		View threesButton = calcActivity.findViewById(R.id.threes);
		threesButton.setEnabled(true);
		View foursButton = calcActivity.findViewById(R.id.fours);
		foursButton.setEnabled(true);
		View fivesButton = calcActivity.findViewById(R.id.fives);
		fivesButton.setEnabled(true);
		View sixsButton = calcActivity.findViewById(R.id.sixs);
		sixsButton.setEnabled(true);
		View sevensButton = calcActivity.findViewById(R.id.sevens);
		sevensButton.setEnabled(true);
		View eightsButton = calcActivity.findViewById(R.id.eights);
		eightsButton.setEnabled(true);
		View ninesButton = calcActivity.findViewById(R.id.nines);
		ninesButton.setEnabled(true);
		View tensButton = calcActivity.findViewById(R.id.tens);
		tensButton.setEnabled(true);
		View jacksButton = calcActivity.findViewById(R.id.jacks);
		jacksButton.setEnabled(true);
		View queensButton = calcActivity.findViewById(R.id.queens);
		queensButton.setEnabled(true);
		View kingsButton = calcActivity.findViewById(R.id.kings);
		kingsButton.setEnabled(true);
		View acesButton = calcActivity.findViewById(R.id.aces);
		acesButton.setEnabled(true);
    	calcActivity.cardPointer = 1;
    	calcActivity.setNextview(calcActivity.cardPointer);
    	TextView tv1 = (TextView) calcActivity.findViewById(R.id.resultPlayer1);
    	tv1.setText("");
    	TextView tv2 = (TextView) calcActivity.findViewById(R.id.resultPlayer2);
    	tv2.setText("");
    }
}
